spring:
  data:
    mongodb:
      authentication-database: test
      username: my_user
      password: password123
      port: 27017
      host: localhost
      database: test
  application:
    name: batch processing server
  boot:
    admin:
      client:
        url: http://localhost:8080
server:
  port: 8082

management:
  metrics:
    export:
      graphite:
        enabled: true
        host: localhost
        port: 2003
        protocol: plaintext
        step: 1s
